// react/client/src/src/views/DocManage/Add.js
import React from 'react';
import {Button, Input, Modal, Form, message} from 'antd';
import {addDoc} from '@/api/doc'

class Add extends React.Component {
    addDoc = async (value)=>{
        try{
            const res = await addDoc({...value,projectId:sessionStorage.getItem('projectId')})
            if(res.state){
                this.refs.form.resetFields()
                this.props.setShow(false)
                this.props.getList()
                message.success(res.msg)
            }else{
                message.error(res.msg)
            }
        }catch (e) {
            message.error(e.message)
        }
    }

    render() {
        return (
            <Modal title='新建'
                   visible={this.props.isShow}
                   onCancel={()=>{
                       this.props.setShow(false)
                   }}
                   footer={null}>
                <Form onFinish={this.addDoc} ref='form'>
                    <Form.Item name='title' rules={[{required: true, message: '请输入活动标题!'}]}>
                        <Input placeholder='请输入活动标题' allowClear={true} maxLength={50}/>
                    </Form.Item>
                    <Form.Item name='url' rules={[{required: true, message: '请输入活动url!'}]}>
                        <Input placeholder='请输入活动url' allowClear={true} maxLength={500}/>
                    </Form.Item>
                    <Form.Item>
                        <Button type='primary' htmlType='submit' block>新建</Button>
                    </Form.Item>
                </Form>
            </Modal>
        )
    }
}

export default Add

// vue/client/src/src/view/DocManage/Add.vue
<template>
    <div class="wrap" >
      <el-form :model="form" ref="ruleForm" label-width="100px">
        <el-form-item label="标题">
          <el-input v-model="form.title" placeholder="请输入标题" maxlength="50"></el-input>
        </el-form-item>
        <el-form-item label="活动URL">
          <el-input v-model="form.url" placeholder="请输入活动URL" maxlength="200"></el-input>
        </el-form-item>
        <el-row class="btn">
          <el-button type="primary" @click="addData">添加</el-button>
        </el-row>
      </el-form>
    </div>
</template>

<script>
import {addDoc} from '@/api/doc'
export default {
  name: 'doc-add',
  data () {
    return {
      form: {
        title: '',
        url: ''
      }
    }
  },
  methods: {
    addData () {
      addDoc(this.form).then(res => {
        if (res.state) {
          this.$message({
            message: '添加成功',
            type: 'success'
          })
          this.$emit('flush')
        }
      })
    }
  }
}
</script>

<style scoped>
  .btn button{
    width: 100%;
  }
</style>
